theme: jekyll-theme-cayman
title: Kings Throne
description: Some info for playing this Android and iOS game
show_downloads: false
google_analytics: G-2H7YYL1YT3
plugins:
  - jemoji
exclude:
- Gemfile
- Gemfile.lock
- .gitignore
- .vscode